# Model, Instrument, Cal Event info
VENDOR_MAX_LENGTH = 30
MODEL_NUM_MAX_LENGTH = 40
DESC_MAX_LENGTH = 100
COMMENT_MAX_LENGTH = 2000
CALIBRATION_FREQUENCY_MAX_LENGTH = 10
SERIAL_NUM_MAX_LENGTH = 40
CAL_FREQUENCY_MAX_DURATION = 3653

CATEGORY_NAME_MAX_LENGTH = 30

# User Limits
USERNAME_MAX_LENGTH = 128
FIRST_NAME_MAX_LENGTH = 128
LAST_NAME_MAX_LENGTH = 128
PASSWORD_MAX_LENGTH = 256
EMAIL_MAX_LENGTH = 320
