# Generated by Django 3.1.5 on 2021-02-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('calibration_frequency', models.IntegerField(default=0)),
            ],
        ),
    ]