# Generated by Django 3.1.6 on 2021-03-05 02:17

import backend.tables.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment', models.CharField(blank=True, max_length=2000)),
                ('file', models.FileField(null=True, upload_to='cal_event_artifacts')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.IntegerField(default=backend.tables.models.Instrument.default_asset_tag, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('serial_number', models.CharField(blank=True, max_length=40)),
                ('comment', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=30)),
                ('model_number', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=2000)),
                ('calibration_frequency', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3653)])),
            ],
            options={
                'unique_together': {('vendor', 'model_number')},
            },
        ),
        migrations.CreateModel(
            name='LoadBankCalibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_inspection', models.BooleanField(blank=True, default=False)),
                ('auto_cutoff', models.BooleanField(blank=True, default=False)),
                ('alarm', models.BooleanField(blank=True, default=False)),
                ('recorded_data', models.BooleanField(blank=True, default=False)),
                ('printer', models.BooleanField(blank=True, default=False)),
                ('cal_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.calibrationevent')),
                ('shunt_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lb_shunt', to='tables.instrument')),
                ('voltmeter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lb_voltmeter', to='tables.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoadVoltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vr', models.FloatField()),
                ('va', models.FloatField()),
                ('test_voltage', models.FloatField()),
                ('vr_error', models.FloatField(null=True)),
                ('va_error', models.FloatField(null=True)),
                ('vr_ok', models.BooleanField(default=False)),
                ('va_ok', models.BooleanField(default=False)),
                ('lb_cal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.loadbankcalibration')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('item_models', models.ManyToManyField(blank=True, to='tables.ItemModel')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('instruments', models.ManyToManyField(blank=True, to='tables.Instrument')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='item_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.itemmodel'),
        ),
        migrations.AddField(
            model_name='calibrationevent',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.instrument'),
        ),
        migrations.AddField(
            model_name='calibrationevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoadCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.CharField(max_length=100)),
                ('cr', models.FloatField()),
                ('ca', models.FloatField()),
                ('ideal', models.FloatField()),
                ('cr_error', models.FloatField(null=True)),
                ('ca_error', models.FloatField(null=True)),
                ('index', models.IntegerField()),
                ('cr_ok', models.BooleanField(default=False)),
                ('ca_ok', models.BooleanField(default=False)),
                ('lb_cal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.loadbankcalibration')),
            ],
            options={
                'unique_together': {('lb_cal', 'load')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('item_model', 'serial_number')},
        ),
    ]
