# Generated by Django 3.1.5 on 2021-02-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('calibration_frequency', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.model')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.user')),
            ],
        ),
    ]
