# Generated by Django 3.1.6 on 2021-03-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadbankcalibration',
            name='shunt_meter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadbankcalibration',
            name='voltmeter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
