# Generated by Django 3.1.5 on 2021-02-02 19:11

from django.db import migrations


def create_data(apps, schema_editor):
    ItemModel = apps.get_model('backend.tables', 'ItemModel')
    ItemModel(vendor="V 001", model_number="M 001", description="model descrip", comment="", calibration_frequency=180).save()


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
