# Generated by Django 3.1.5 on 2021-02-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='calibration_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
