# Generated by Django 3.1.6 on 2021-02-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
