# Generated by Django 3.1.6 on 2021-02-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='model_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='vendor',
            field=models.CharField(max_length=30),
        ),
    ]
