# Generated by Django 3.1.5 on 2021-02-02 01:10

from django.db import migrations


def create_data(apps, schema_editor):
    ItemModel = apps.get_model('tables', 'ItemModel')
    ItemModel(vendor="V 001", model_number="M 001", description="desc", comment="", calibration_frequency=150).save()


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210201_1136'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
