# Generated by Django 3.1.6 on 2021-02-15 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210212_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='calibration_frequency',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3653)]),
        ),
    ]
