# Generated by Django 3.1.5 on 2021-02-03 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, validators=[django.core.validators.EmailValidator]),
        ),
    ]
