# Generated by Django 3.1.5 on 2021-02-12 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210210_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='calibration_frequency',
            field=models.IntegerField(default=0, max_length=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='model_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='vendor',
            field=models.CharField(max_length=30),
        ),
    ]
