# Generated by Django 3.1.6 on 2021-04-06 13:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0003_auto_20210325_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationevent',
            name='approval_status',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CalibrationApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment', models.CharField(blank=True, max_length=2000)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cal_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.calibrationevent')),
            ],
        ),
    ]
