# Generated by Django 3.1.5 on 2021-02-02 02:08

from django.db import migrations


def create_data(apps, schema_editor):
    model = apps.get_model('tables', 'ItemModel')
    model(vendor="V 001", model_number="M 001", description="desc", comment="", calibration_frequency=150).save()


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_tables'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
