# Generated by Django 3.1.6 on 2021-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210305_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
