# Generated by Django 3.1.6 on 2021-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210215_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('item_models', models.ManyToManyField(blank=True, to='tables.ItemModel')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('instruments', models.ManyToManyField(blank=True, to='tables.Instrument')),
            ],
        ),
    ]
