# Generated by Django 3.1.6 on 2021-04-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20210406_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('fieldtype', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100, null=True)),
                ('plaintext', models.CharField(max_length=5000, null=True)),
                ('expected_string', models.CharField(max_length=200, null=True)),
                ('expected_min', models.FloatField(null=True)),
                ('expected_max', models.FloatField(null=True)),
                ('actual_string', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_float', models.FloatField(null=True)),
                ('actual_bool', models.BooleanField(null=True)),
                ('value_okay', models.BooleanField(default=False)),
                ('cal_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.calibrationevent')),
                ('itemmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.itemmodel')),
            ],
            options={
                'unique_together': {('itemmodel', 'index')},
            },
        ),
    ]
