# Generated by Django 3.1.6 on 2021-02-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_usertype'),
        ('tables', '0004_instrumentcategory_itemmodelcategory'),
    ]

    operations = [
    ]
