# Generated by Django 3.1.6 on 2021-03-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20210305_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('load_bank', 'load_bank')], max_length=30, unique=True)),
                ('models', models.ManyToManyField(blank=True, to='tables.ItemModel')),
            ],
        ),
    ]
