# Generated by Django 3.1.6 on 2021-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20210406_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodelcategory',
            name='calibrated_with',
            field=models.ManyToManyField(blank=True, related_name='calibrator_categories_set', to='tables.ItemModel'),
        ),
    ]
