# Generated by Django 3.1.6 on 2021-03-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_merge_20210225_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationevent',
            name='file',
            field=models.FileField(blank=True, upload_to='cal_event_artifacts'),
        ),
    ]
