# Generated by Django 3.1.6 on 2021-02-28 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_merge_20210225_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBankCalibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_inspection', models.BooleanField(blank=True, default=False)),
                ('auto_cutoff', models.BooleanField(blank=True, default=False)),
                ('alarm', models.BooleanField(blank=True, default=False)),
                ('recorded_data', models.BooleanField(blank=True, default=False)),
                ('printer', models.BooleanField(blank=True, default=False)),
                ('cal_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.calibrationevent')),
                ('shunt_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lb_shunt', to='tables.instrument')),
                ('voltmeter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lb_voltmeter', to='tables.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='LoadCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.CharField(max_length=100)),
                ('cr', models.FloatField()),
                ('ca', models.FloatField()),
                ('ideal', models.FloatField()),
                ('cr_error', models.FloatField()),
                ('ca_error', models.FloatField()),
                ('lb_cal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.loadbankcalibration')),
            ],
            options={
                'unique_together': {('lb_cal', 'load')},
            },
        ),
    ]
