# Generated by Django 3.1.6 on 2021-04-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_itemmodelcategory_calibrated_with'),
        ('tables', '0005_calibrationformfield'),
    ]

    operations = [
    ]
