# Generated by Django 3.1.6 on 2021-03-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20210305_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationevent',
            name='file_type',
            field=models.CharField(choices=[('None', 'None'), ('Artifact', 'Artifact'), ('Load Bank', 'Load Bank')], default='None', max_length=20),
        ),
    ]
