# Generated by Django 3.1.6 on 2021-04-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_merge_20210412_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='file_type',
            field=models.CharField(choices=[('None', 'None'), ('Artifact', 'Artifact'), ('Load Bank', 'Load Bank'), ('Klufe', 'Klufe'), ('Form', 'Form')], default='None', max_length=20),
        ),
    ]
