# Generated by Django 3.1.6 on 2021-04-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210412_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationformfield',
            name='expected_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
