# Generated by Django 3.1.6 on 2021-02-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210205_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='model_number',
            field=models.CharField(default='demo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='vendor',
            field=models.CharField(default='demo', max_length=100),
            preserve_default=False,
        ),
    ]
