# Generated by Django 3.1.6 on 2021-03-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210228_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadVoltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vr', models.FloatField()),
                ('va', models.FloatField()),
                ('test_voltage', models.FloatField()),
                ('vr_error', models.FloatField(null=True)),
                ('va_error', models.FloatField(null=True)),
                ('vr_ok', models.BooleanField(default=False)),
                ('va_ok', models.BooleanField(default=False)),
                ('lb_cal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.loadbankcalibration')),
            ],
        ),
    ]
