# Generated by Django 3.1.6 on 2021-02-08 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20210206_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
