# Generated by Django 3.1.6 on 2021-02-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20210208_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationevent',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
